source ~/Documents/dotfiles/antigen/antigen.zsh

BASE16_SHELL="$HOME/.config/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
PURE_GIT_UNTRACKED_DIRTY=0
PURE_GIT_PULL=0

antigen bundle sindresorhus/pure
antigen apply

autoload -U compinit promptinit
compinit

autoload -U edit-command-line && zle -N edit-command-line
autoload -U url-quote-magic && zle -N self-insert url-quote-magic
autoload -U select-word-style && select-word-style bash

bindkey -v
bindkey "^[[A"    up-line-or-search                    # up
bindkey "^[[B"    down-line-or-search                  # down
bindkey "^K"      kill-whole-line                      # ctrl-k
bindkey "^R"      history-incremental-search-backward  # ctrl-r
bindkey "^A"      beginning-of-line                    # ctrl-a
bindkey "^E"      end-of-line                          # ctrl-e
bindkey "^D"      delete-char                          # ctrl-d
bindkey "^F"      forward-char                         # ctrl-f
bindkey "^B"      backward-char                        # ctrl-b
bindkey "^xe"     edit-command-line
bindkey "^x^e"    edit-command-line

setopt print_exit_value
setopt correct
setopt menu_complete
unsetopt nomatch
unsetopt share_history
unsetopt inc_append_history
zstyle ':completion:*' special-dirs '[[ $PREFIX = (../)#(|.|..) ]] && reply=(..)'
zstyle ':completion:*' menu select
zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle ':completion:*:rm:*' ignore-line yes
zstyle ':completion:*:mv:*' ignore-line yes
zstyle ':completion:*:cp:*' ignore-line yes

alias ll="ls -l --color"

export EDITOR=vim
export TERM=xterm-256color
export CLICOLOR=1
export LSCOLORS=Gxfxcxdxbxegedabagacad
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='3;33'
export LESS='--ignore-case --raw-control-chars'
export PAGER='less'
export PROJECTS_HOME=$HOME/Documents/Projects/

function vir
{
  tmux new-session -d -s vir
  tmux new-window -t vir:2 -n 'vim' "vim $*"
  tmux split-window -d -t vir:2 -p 25 -v 'lein repl'
  tmux attach-session -t vir
}

function bigfiles
{
  tree -ah --du . | ack '\[(\d{3,}M|\d+.*G)\]'
}
